CREATE DATABASE IF NOT EXISTS 3size_db;

USE 3size_db;

CREATE TABLE IF NOT EXISTS 3size_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    bust INT NOT NULL,
    waist INT NOT NULL,
    hip INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
